### ISSUE TITLE
[OS X 10.11]: Conflicting types for lock_try

### ISSUE THREAD

**Issue by altamic** [orangeduck/Cello#102]
I was trying to use your wonderful libcello for a simple C project on my MacBook but I could not do that for a name clash with the lock_try function identifier.
I attach the images for your reference.

![screen shot 2016-03-19 at 18 29 40](https://cloud.githubusercontent.com/assets/15282/13900232/c8f52ad6-ee01-11e5-8d11-4ba834aa0d93.png)

Below there is the OS X system function:

![screen shot 2016-03-19 at 18 29 06](https://cloud.githubusercontent.com/assets/15282/13900249/fe290ed4-ee01-11e5-8e27-2054a8ab2245.png)

Could you fix the problem?

Thank you for your project!

**Comment by orangeduck** [comment]
Opps - this is a bit unexpected. 

I guess I will have to rename the `lock_try` function. For now - assuming you are not using this function you can comment it out from the Cello header and it should be fine.

- Dan

**Comment by orangeduck** [comment]
Fixed in  fb48fae
