### ISSUE TITLE
Array of Array

### ISSUE THREAD

**Issue by shakna-israel** [orangeduck/Cello#105]
Does Cello support Array of Arrays?

I'm not sure how one would go about initialising it, if it were possible...

```
var x = new(Array, new(Array, Int));
```

**Comment by orangeduck** [comment]
At the moment this is done like `var x = new(Array, Array);`. Then when you construct each element you can specify the subtype `push(x, new(Array, Int));`.

**Comment by shakna-israel** [comment]
Sounds good.
