### ISSUE TITLE
Foreach... Range forever 

### ISSUE THREAD

**Issue by shakna-israel** [orangeduck/Cello#106]
Running a foreach against a range creates an infinite loop, unless I'm doing something crazy. 

Minimal example, using Cello from master branch:

```
#include "Cello.h"

int main(int argc, char** argv) 
{
  foreach(i in range($I(10)))
  {
    println("Hi.");
  } 
  return 0; // Never gets here. 
} 
```

I suspect that the range is reinstantiated with the Int on each loop.

**Comment by orangeduck** [comment]
Hi,

I'm unable to reproduce this. What compiler/platform etc are you using.

- Dan

**Comment by shakna-israel** [comment]
gcc 4.9.2-10

ARMv7 (64-bit), Debian Jessie

Compiled with:

```
gcc -std=gnu99 -lpthread -lCello RangedTest.c -o RangedTest
```

When compiling Cello, one warning is emitted:

```
src/Type.c: In function ‘Type_New’:
src/Type.c:199:55: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   t[cache_entries+1] = (struct Type){ NULL, "__Size", (var)c_int(size) };
```

**Comment by shakna-israel** [comment]
The Cello warning looks like it's the issue.

For some reason, ```int64_t``` is treated as ```int32_t```, but ```uint64_t``` is treated properly.

Fixed it by just using 32bit numbers, as limiting as that is.
