### ISSUE TITLE
How do one "extends" a type?

### ISSUE THREAD

**Issue by stevefan1999** [orangeduck/Cello#113]
So I was trying to make traditional inheritance chain in Cello but failed to find such examples in both documentation and code examples, not even in tests.

I was trying to do this:
```c

struct FooMorph {
    void(*ReadList)(var);
};

struct Foo {
    int x;
    struct List *l;
};

struct Bar {
    char unused[];
};

void Foo_Ctor(var self) {
    struct Foo *this = self;
    printf("Hello Foo from %p!\n", this);
    this->x = 10;
    this->l = new(List, Float, $F(0.01), $F(5.12));
}

void Foo_ReadList(var self) {
    struct Foo *this = self;
    show(this->l);
}

void Foo_Dtor(var self) {
    struct Foo *this = self;
    printf("Goodbye Foo from %p!\n", this);
    del(this->l);
}

var FooMorph = Cello(FooMorph);
var Foo = Cello(Foo,
    Instance(New, Foo_Ctor, Foo_Dtor), 
    Instance(FooMorph, Foo_ReadList)
);

var Bar = Cello(Bar,
    Instance(Foo)
);

```
But clearly in `Bar`, dispatch function needs to be supplied. Is there anyway to tell the Cello type system to use/extend Foo's type for Bar?

I see that in the docs, there're `Derive` but not `Extend`, meaning that classes cannot inherit each other and can only inherit (functionally equivalent of) interfaces?

**Comment by stevefan1999** [comment]
Okay, it seems like I misread something :)

```
var Bar = Cello(Bar,
    Instance(New, Foo_Ctor, Foo_Dtor),
    Instance(Foo, Foo_ReadList)
);

// So now Bar now extends what Foo have, and behaves like Foo
// I believe this is a kind of duck typing
```

So far yes, I think vtables must be manually placed...

**Comment by orangeduck** [comment]
Yes Cello only supports interface type inheritance not family type inheritance.

**Comment by stevefan1999** [comment]
BTW, I think this kind of late binding looks like prototype :p
