### ISSUE TITLE
pop semantics?

### ISSUE THREAD

**Issue by ghost** [orangeduck/Cello#115]
I am playing with Cello and I wanted to implement a Queue, basically as locked Push class. But pop() doesn't return the popped value. So I wonder if pop and pop_at could return a value? Is this wanted? I would try to do a PR.

**Comment by orangeduck** [comment]
Hey,

So the reason that the `pop` function doesn't return a `var` is that in most containers if you `pop` the object then it is removed from the container and no longer exists in memory - and so the `var` returned by `pop` no longer points to anything.

So if you really want to `pop` something from a container what you really need to do is `assign` it to a local variable first:

```
var my_list = new(Array, Int, $I(10), $I(20), $I(30));
var x = $I(0);
assign(x, get(my_list, -1));
pop(x);
```

You might be able to come up with a better interface for the Queue but you'll have to think about who owns the memory of the object once it is popped.

Dan

**Comment by ganwell** [comment]
Thanks Dan. I just realized that Cello has quite a strange learning curve: a lot of things feel familiar, but you have to unlearn certain concepts. I was only thinking about heap-objects not 'stack-objects' which have to be transferred somehow. I still really like it.

**Comment by orangeduck** [comment]
Yes definitely - there are some things in C you can't really work around (memory management being one) which makes some things in Cello quite awkward as they appear high level but you still need to think about the low level details! This is one of them :)
