### ISSUE TITLE
Append Char

### ISSUE THREAD

**Issue by shakna-israel** [orangeduck/Cello#116]
I'm in a position where I want to append a single C char to a Cello String.

From what I can see, Cello doesn't really have a type for ```char```, so the ```String_append``` won't work.

Do I need to use ```c_str``` to get the ```char*```, malloc it, add the char, and convert it back?

**Comment by orangeduck** [comment]
Yeah, or alternatively you could convert the char to a null terminated char*, wrap it in a String type, and then append that.

**Comment by shakna-israel** [comment]
Thanks
