### ISSUE TITLE
Missing Git tag for 2.1.0 release

### ISSUE THREAD

**Issue by jetm** [orangeduck/Cello#126]
Please, could you add the Git tag for 2.1.0 release in GitHub?

The Git tags are useful. With them, I will know when to update the libcello package for Arch Linux.

Thanks, Javier

**Comment by orangeduck** [comment]
Thanks @jetm - I've added a tag to the latest commit.

**Comment by jetm** [comment]
@orangeduck Thank you. I have updated the package
