### ISSUE TITLE
Non-portable `__has_feature` usage 

### ISSUE THREAD

**Issue by fuhsnn** [orangeduck/Cello#147]
Hi, the latest commit 48f7c04c0d9319a90a301d0a37de75678e645acf introduced the use of `__has_feature` operator without guarding its availability with `#if defined()` checks, this is not portable and will fail on non-clang compilers and GCC <= 13, which I believe is still widely in use. 

Here is a Godbolt session to illustrate the issue: https://godbolt.org/z/Pfhzcnrsx

The behavior is in line with the similar `__has_attribute` and `__has_include` operators, and was explicitly noted in GCC doc.
https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005fattribute.html
https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005finclude.html

**Comment by orangeduck** [comment]
Thanks for the report. Would you be able to make a PR fixing this?
