### ISSUE TITLE
Name collisions when building inside Xcode 6.2 beta

### ISSUE THREAD

**Issue by zhangchn** [orangeduck/Cello#77]
Hi,

I just tried to embed and build libCello in an Xcode project. Using default build settings, name collision occurred, as Xcode betas are using clang modules to accelerate building, e.g., `clear()`s from Prelude.h and {SDK ROOT}/usr/include/curses.h collided.

This issue could be circumvented by disabling Modules feature in Build Settings -> Apple LLVM 6.0 - Languages - Modules -> Enable Modules (C and Objective-C).

**Comment by orangeduck** [comment]
Hi @zhangchn,

Thanks for the heads up. I will try to find a fix for this for the next release (probably just a renaming).

- Dan
