### ISSUE TITLE
Cannot compile in mingw due to missing header file.

### ISSUE THREAD

**Issue by polyglotCipher** [orangeduck/Cello#86]
cc src/Alloc.c -c -I ./include -std=gnu99 -Wall -Wno-unused -o obj/Alloc.o
    In file included from src/Alloc.c:1:0:
    ./include/Cello.h:120:21: fatal error: DbgHelp.h: No such file or directory
     #include <DbgHelp.h>
                         ^
    compilation terminated.
    make: *** [obj/Alloc.o] Error 1

**Comment by orangeduck** [comment]
Hey,

What version of MinGW are you using? I seem to have DbgHelp on my setup but I don't know how much I've screwed around with it.

- Dan

**Comment by polyglotCipher** [comment]
`0.6.4-beta-20131004-1`
I don't think the versioning if MinGW is an issue, though, as that is the latest version and the individual packages that it can install are updated more frequently than the actual manager and I've downloaded those just a few weeks ago.

However, I really have NO idea. I have trouble finding ANYTHING about `DbgHelp.h` and I've never heard of it.

**Comment by orangeduck** [comment]
Hi,

Hopefully this is fixed in 5d9ac93841ae1ec25d088e67e5e4db8c28e5e231 where I made the stacktrace conditional on the `DbgHelp` library being present. Would you be able to verify? I'm using MinGW64 which I think comes with this library but it sounds like you are maybe still using the 32-bit version which I don't think has it.

Thanks,

- Dan

**Comment by polyglotCipher** [comment]
No problems during compilation with this one.

I tried compiling some of the examples, one just needs to pass the `-DCELLO_NSTRACE` flag to `gcc` and it works. You might want to document that in some way.

Also, are you sure you want the debugger flags in there? (`-g -ggdb`)
Nothing wrong with it. Just making sure it's on purpose.

**Comment by orangeduck** [comment]
I'll add some info to the website. Yeah I think there is nothing to lose by always including the debug information.

Thanks for the help.
