### ISSUE TITLE
cell2.0.3  threads test example compile failed with mingw on win7 

### ISSUE THREAD

**Issue by sotoup** [orangeduck/Cello#88]
Hi
   When I compiling example threads , erro found below:
      threads.c: In function 'Cello_Main':
      threads.c:14:15: error: expected expression before ',' token
      make: *** [all] Error 1
 
compile command:
 gcc -DCELLO_NSTRACE  -std=c99 -o threads  -I../include threads.c -L../ -lCello

 gcc -v

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/4.7.2/lto-wrapper.exe
Target: mingw32
Configured with: ../gcc-4.7.2/configure --enable-languages=c,c++,ada,fortran,obj
c,obj-c++ --disable-sjlj-exceptions --with-dwarf2 --enable-shared --enable-libgo
mp --disable-win32-registry --enable-libstdcxx-debug --disable-build-poststage1-
with-cxx --enable-version-specific-runtime-libs --build=mingw32 --prefix=/mingw
Thread model: win32
gcc version 4.7.2 (GCC)

**Comment by orangeduck** [comment]
Hi sotoup,

Do you get the error if you compile with `-std=gnu99`? Cello requires the gnu extension for pasting variable argument macros: https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html

Thanks,

Dan

**Comment by sotoup** [comment]
Hi orangeduck:
    Thanks for your answer.
    When I compiling with -std=gnu, it goes fine.
