### ISSUE TITLE
Feature request: Read typeclass

### ISSUE THREAD

**Issue by katyo** [orangeduck/Cello#90]
I can see `Show` typeclass, It's very nice and useful thing. But the `Read` typeclass is missing (Haskell-like thing), so we can't read Cello vars back from string, only show it.

**Comment by katyo** [comment]
Oh, sorry. There is already implemented a look/scan methods.

**Comment by orangeduck** [comment]
For other people who find this issue the revelant class is still `Show` and more specifically the `look` method as documented [here](http://libcello.org/learn/show). This is what allows for `scanlike` methods to be used.
