### ISSUE TITLE
Add Git tags to generate Cello releases in GitHub

### ISSUE THREAD

**Issue by jetm** [orangeduck/Cello#94]
Hello,

Could you add Git tags to generate [Cello releases](https://github.com/orangeduck/Cello/releases) in GitHub?

Thanks in advance.

**Comment by orangeduck** [comment]
Hi jetm,

I've added a tag/release for the current version. I hope that is okay.

Thanks,

Dan

**Comment by jetm** [comment]
Hi @orangeduck,

Release says 2.0 and the tags says 2.0.3. I think for now is okay.

Thanks,
jetm
